name: SQL Script Validation

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  verify-sql:
    name: SQL Script Validation
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bd2ano
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to start
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -U postgres; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL to start..."
            sleep 3
          done

      - name: Execute SQL script
        env:
          PGPASSWORD: postgres
        run: |
          echo "Running script.sql..."
          if ! psql -h localhost -U postgres -d bd2ano -f script.sql; then
            echo "Error executing script.sql"
            exit 1
          fi
          echo "Script executed successfully!"

      - name: Verify table creation
        env:
          PGPASSWORD: postgres
        run: |
          echo "Checking if main tables exist..."
          tables=("factory" "user_account" "payment" "subscription" "access_type")
          for t in "${tables[@]}"; do
            exists=$(psql -h localhost -U postgres -d bd2ano -tAc "SELECT to_regclass('public.$t');" | xargs)
            if [ "$exists" = "$t" ]; then
              echo "Table $t found!"
            else
              echo "Table $t was not created correctly!"
              echo "Showing all tables for debugging:"
              psql -h localhost -U postgres -d bd2ano -c "\dt"
              exit 1
            fi
          done

      - name: Verify functions and procedures
        env:
          PGPASSWORD: postgres
        run: |
          echo "Checking if functions and procedures were created..."
          functions=("get_factory_active_payment" "get_user_accounts_by_factory" "trg_changed_at")
          for f in "${functions[@]}"; do
            exists=$(psql -h localhost -U postgres -d bd2ano -tAc "SELECT routine_name FROM information_schema.routines WHERE routine_name='$f';")
            if [ "$exists" = "$f" ]; then
              echo "Function $f created successfully!"
            else
              echo "Function $f not found!"
              exit 1
            fi
          done

      - name: Check SQL formatting (optional)
        run: |
          pip install sqlfluff
          sqlfluff lint script.sql --dialect postgres || true
